### ISSUE TITLE
FR2: Need single script to run in both Windows batch and Linux Bash

### ISSUE THREAD

**Issue by mikelaud** [kocherovms/metracer#28]
FR2: Need single script to run in both Windows batch and Linux Bash:
http://stackoverflow.com/questions/17510688/single-script-to-run-in-both-windows-batch-and-linux-bash

**Comment by kocherovms** [comment]
It's simpler to have two separate scripts:
- metracer.sh - for *nix systems
- metracer.cmd - for Windows

This way it's very clear for user which one to use. Also this would render a better integration with OS

**Comment by kocherovms** [comment]
Fixed in revs:
1928056ba549cdad6b0ea6b291ba04d62d75a348
f080ca5265bbe276f9002135969f8c891cc2a0ff
83328c7c7d255bce50708949dbb8afe5243bfe5d
2bd7d32b4457eb63e69f8fa1877c2de44449d86d
