### ISSUE TITLE
Unable to view complete data, getting "too long value"  

### ISSUE THREAD

**Issue by Kartikvk1996** [kocherovms/metracer#67]
Hi,

When I attach the tracer and try to print I am getting below message.

org.postgresql.jdbc.PgConnection.prepareStatement(sql = SELECT id FROM abc WHE... (too long value of 47 syms)

I am not able to see complete SQL query. I tried changing the static variable "MaxDumpLength" value present in ObjectDumper.java from 32 to 255, but still, the output is the same. 

Can anyone assist me here?

**Comment by kocherovms** [comment]
Hi, 

There is an option "-m" - it configures MaxDumpLength in runtime. 
Try providing "... -m 4096" for in command line.

**Comment by Kartikvk1996** [comment]
"-m" argument worked for me. Thanks, @kocherovms
